server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/exp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: admin
#    url: jdbc:mysql://localhost:3307/exp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

##App properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
